--los campos no forzosamente tienen que llamarse como los campos en el archivo de carga

--drop table TAGOBDATCU2;
/*CREATE TABLE TAGOBDATCU2
(
  FXPAISCU NUMBER(5, 0) NOT NULL 
, FXCANALCU NUMBER(5, 0) NOT NULL 
, FXSUCURSALCU NUMBER(10, 0) NOT NULL 
, FXFOLIOCU NUMBER(20, 0) NOT NULL 
, FXNOMBRECLIENTE VARCHAR2(200 BYTE) NOT NULL 
, FXRFCCLIENTE VARCHAR2(20 BYTE) NOT NULL 
, FXDIRECCIONFISCAL VARCHAR2(300 BYTE) DEFAULT 'DOMICILIO CONOCIDO' NOT NULL 
, FXCODIGOPOSTALFISCAL VARCHAR2(10 BYTE) NOT NULL 
, FXMODIFICO DATE NOT NULL 
, FXUSRMODIFICO VARCHAR2(30 BYTE) NOT NULL 
) tablespace users;
CREATE UNIQUE INDEX IX_GOBDATCU2_01 ON TAGOBDATCU2 (FXPAISCU, FXCANALCU, FXSUCURSALCU, FXFOLIOCU) tablespace users;*/

select count(*) from TAGOBDATCU2